In [13]:
import minitorch
import minitorch.nn as nn


class Model(nn.Module):
    def __init__(self, in_feat, out_feat):
        super().__init__()
        self.layer1 = nn.Linear(in_feat, 5)
        self.layer2 = nn.Linear(5, out_feat)

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        return x
    
model = Model(10, 1)


out = model(minitorch.Tensor([[1.0] * 10]))

print(out)
print(model.layer1.weight)
print(model.layer2.weight)


print("Parameters:")
for param in model.parameters():
    print(param)

model.zero_grad()
print("Gradients after zero_grad():")
for param in model.parameters():
    print(param.grad)

Tensor(data=[[-1.00172021]], grad=[[0.]])
Tensor(data=[[ 0.14003062 -0.20350343 -0.05499442 -0.16049512  0.22230381]
 [-0.0056463  -0.10300515 -0.30295437 -0.18999991 -0.00689495]
 [ 0.20884031  0.0528607   0.05931245 -0.21239072  0.00466216]
 [ 0.17719747 -0.20388824  0.0839246   0.15690937 -0.12467047]
 [ 0.25972547 -0.02106472 -0.30654619 -0.12929437  0.06939802]
 [ 0.21151011  0.28170195  0.08578709 -0.24353519 -0.03493648]
 [-0.04608633  0.12627643  0.30877085  0.16320949 -0.20618861]
 [ 0.15927876  0.23609642  0.14969818 -0.14499976 -0.01524377]
 [ 0.07665637 -0.02589069 -0.1416269  -0.28484375 -0.27706293]
 [ 0.17912315 -0.07926064  0.1357386   0.15036807 -0.14182396]], grad=[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]])
Tensor(data=[[-0.23282586]
 [ 0.14609368]
 [-0.09886001]
 [ 0.23542634]
 [ 0.30920327]], grad=[[0.]
 [0.]
 [0.]
 [0.]
 [0.]])
P

In [14]:
from minitorch.nn import Linear, Module
from minitorch import Tensor

# class Model(Module):
#     def __init__(self, in_feat, out_feat):
#         super().__init__()
#         self.layer1 = Linear(in_feat, 5)
#         self.layer2 = Linear(5, out_feat)

#     def forward(self, x):
#         x = self.layer1(x)
#         x = self.layer2(x)
#         return x

# x = Tensor([[1.0 for _ in range(10)]])
# model = Model(10, 1)
# out = model(x)
print("Output:", out)

print("Parameters:")
for param in model.parameters():
    print(param)

model.zero_grad()
print("Gradients after zero_grad():")
for param in model.parameters():
    print(param.grad)


Output: Tensor(data=[[-1.00172021]], grad=[[0.]])
Parameters:
Tensor(data=[[ 0.14003062 -0.20350343 -0.05499442 -0.16049512  0.22230381]
 [-0.0056463  -0.10300515 -0.30295437 -0.18999991 -0.00689495]
 [ 0.20884031  0.0528607   0.05931245 -0.21239072  0.00466216]
 [ 0.17719747 -0.20388824  0.0839246   0.15690937 -0.12467047]
 [ 0.25972547 -0.02106472 -0.30654619 -0.12929437  0.06939802]
 [ 0.21151011  0.28170195  0.08578709 -0.24353519 -0.03493648]
 [-0.04608633  0.12627643  0.30877085  0.16320949 -0.20618861]
 [ 0.15927876  0.23609642  0.14969818 -0.14499976 -0.01524377]
 [ 0.07665637 -0.02589069 -0.1416269  -0.28484375 -0.27706293]
 [ 0.17912315 -0.07926064  0.1357386   0.15036807 -0.14182396]], grad=[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]])
Tensor(data=[-0.04306365 -0.12522379 -0.15366652 -0.08165947 -0.30002456], grad=[0. 0. 0. 0. 0.])
Tensor(da