In [1]:
import minitorch
import minitorch.nn as nn
from minitorch.nn import Linear, Module
from minitorch import Tensor
from minitorch.nn.parameter import Parameter

class MiniTorchModel(Module):
    def __init__(self, in_feat, out_feat):
        super().__init__()
        self.layer1 = Linear(in_feat, 3)
        self.layer2 = Linear(3, out_feat)

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        return x

minitorch_model = MiniTorchModel(2, 1)
print(minitorch_model)

print('-'*50)


input_tensor = Tensor([[1.0, 1.0]])

out_minitorch = minitorch_model(input_tensor)

print("MiniTorch Model Output:")
print(out_minitorch)

print("MiniTorch Model Parameters:")
for param in minitorch_model.parameters():
    print(param)

print('-' * 50)

# Test Tensor
t = Tensor([[1.0, 1.0]])
print(t)

p = Parameter(Tensor([[1.0, 1.0]]))
print(p)

MiniTorchModel(
  (layer1): Linear(in_features=2, out_features=3, bias=True),
  (layer2): Linear(in_features=3, out_features=1, bias=True),
)
--------------------------------------------------
MiniTorch Model Output:
tensor([[0.1043]], requires_grad=True)
MiniTorch Model Parameters:
Parameter containing:
tensor([[-0.5117 -0.534   0.3201]
 [-0.6215  0.524   0.1014]], requires_grad=True)
Parameter containing:
tensor([-0.5399  0.6092  0.3487], requires_grad=True)
Parameter containing:
tensor([[-0.1149]
 [-0.3379]
 [-0.3367]], requires_grad=True)
Parameter containing:
tensor([0.3738], requires_grad=True)
--------------------------------------------------
tensor([[1. 1.]])
Parameter containing:
tensor([[1. 1.]], requires_grad=True)


In [2]:
import torch

class TorchModel(torch.nn.Module):
    def __init__(self, in_feat, out_feat):
        super().__init__()
        self.layer1 = torch.nn.Linear(in_feat, 3)
        self.layer2 = torch.nn.Linear(3, out_feat)

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        return x

torch_model = TorchModel(2, 1)
out_torch = torch_model(torch.tensor([[1.0] * 2]))


print(torch_model)
print('-' * 50)


print("Torch Model Output:")
print(out_torch)

print("Torch Model Parameters:")
for param in torch_model.parameters():
    print(param)

print('-'*50)

t = torch.tensor([[1.0] * 2])
print(t)
print(t.grad)
print(t.requires_grad)

z = torch.tensor([[1.0] * 2], requires_grad=True)
print(z)

p = torch.nn.Parameter(torch.tensor([[1.0] * 2]))
print(p)

TorchModel(
  (layer1): Linear(in_features=2, out_features=3, bias=True)
  (layer2): Linear(in_features=3, out_features=1, bias=True)
)
--------------------------------------------------
Torch Model Output:
tensor([[0.2047]], grad_fn=<AddmmBackward0>)
Torch Model Parameters:
Parameter containing:
tensor([[-0.1887, -0.6597],
        [-0.6384,  0.5586],
        [ 0.5787, -0.5646]], requires_grad=True)
Parameter containing:
tensor([ 0.2758, -0.1707,  0.2190], requires_grad=True)
Parameter containing:
tensor([[ 0.4937, -0.5356, -0.0096]], requires_grad=True)
Parameter containing:
tensor([0.3555], requires_grad=True)
--------------------------------------------------
tensor([[1., 1.]])
None
False
tensor([[1., 1.]], requires_grad=True)
Parameter containing:
tensor([[1., 1.]], requires_grad=True)


In [3]:
from minitorch.nn import Parameter

x = Tensor([[1.0, 2.0]], requires_grad=False)
w = Parameter(Tensor([[3.0], [4.0]]))  # shape: (2,1)
b = Parameter(Tensor([0.1]))  # shape: (1,)

y = x @ w + b
print("Forward output:", y)

y.backward()
print("Gradient of w:\n", w.grad)
print("Gradient of b:\n", b.grad)


Forward output: tensor([[11.1]], requires_grad=True)
Gradient of w:
 [[1.]
 [2.]]
Gradient of b:
 [1.]
