In [ ]:
import sys
sys.path.append('../')

In [ ]:
import minitorch
import torch

In [5]:
a = minitorch.Tensor([[1.0, 2.0], [3.0, 4.0]])
b = minitorch.Tensor([[5.0, 6.0], [7.0, 8.0]])
c = a + b
d = c * a
e = d ** 2
print(e)

t_a = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)
t_b = torch.tensor([[5.0, 6.0], [7.0, 8.0]], requires_grad=True)
t_c = t_a + t_b
t_c.retain_grad()
t_d = t_c * t_a
t_d.retain_grad()
t_e = t_d ** 2
print(t_e)

tensor([[  36.  256.]
 [ 900. 2304.]], requires_grad=True)
tensor([[  36.,  256.],
        [ 900., 2304.]], grad_fn=<PowBackward0>)


In [3]:
e.backward()
print(a.grad)
print(b.grad)
print(c.grad)
print(d.grad)

[[  84.  320.]
 [ 780. 1536.]]
[[ 12.  64.]
 [180. 384.]]
[[ 12.  64.]
 [180. 384.]]
[[12. 32.]
 [60. 96.]]


In [4]:
t_e.backward(gradient=torch.ones_like(t_e.data, dtype=float))
print(t_a.grad)
print(t_b.grad)
print(t_c.grad)
print(t_d.grad)

tensor([[  84.,  320.],
        [ 780., 1536.]])
tensor([[ 12.,  64.],
        [180., 384.]])
tensor([[ 12.,  64.],
        [180., 384.]])
tensor([[12., 32.],
        [60., 96.]])
