In [1]:
import sys
sys.path.append('../')

In [2]:
import minitorch

# check comparison functions of minitorch
x = minitorch.Tensor([1.0, 2.0, 3.0])
y = minitorch.Tensor([2.0, 2.0, 1.0])

# Test greater than
gt_result = x > y
print(gt_result)

# Test less than
lt_result = x < y
print(lt_result)

# Test equal to
eq_result = x == y
print(eq_result)

# Test not equal to
ne_result = x != y
print(ne_result)

tensor([False, False,  True])
tensor([ True, False, False])
tensor([False,  True, False])
tensor([ True, False,  True])


In [3]:
gt_result.dtype

numpy.bool

In [4]:
print(gt_result.dtype)

<class 'numpy.bool'>


In [5]:
# torch boolean array
import torch
torch_x = torch.tensor([1.0, 2.0, 3.0])
torch_y = torch.tensor([2.0, 2.0, 1.0])
# Test greater than with torch
torch_gt_result = torch_x > torch_y
print(torch_gt_result)
# Test less than with torch
torch_lt_result = torch_x < torch_y
print(torch_lt_result)
# Test equal to with torch
torch_eq_result = torch_x == torch_y
print(torch_eq_result)
# Test not equal to with torch
torch_ne_result = torch_x != torch_y
print(torch_ne_result)

tensor([False, False,  True])
tensor([ True, False, False])
tensor([False,  True, False])
tensor([ True, False,  True])


In [6]:
torch_gt_result.dtype

torch.bool

In [7]:
print(torch_gt_result.dtype)

torch.bool
