In [1]:
import sys
sys.path.append('../')

In [2]:
import minitorch
import minitorch.nn as nn

class MiniTorchModel(nn.Module):
    def __init__(self, in_feat, out_feat):
        super().__init__()
        self.layer1 = nn.Linear(in_feat, 3)
        self.layer2 = nn.Linear(3, out_feat)

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        return x

minitorch_model = MiniTorchModel(2, 1)
print(minitorch_model)

print('-'*50)


input_tensor = minitorch.Tensor([[1.0, 1.0]])

out_minitorch = minitorch_model(input_tensor)

print("MiniTorch Model Output:")
print(out_minitorch)

print('-' * 50)

print("MiniTorch Model Parameters:")
for param in minitorch_model.parameters():
    print(param)

print('-' * 50)

MiniTorchModel(
  (layer1): Linear(in_features=2, out_features=3, bias=True),
  (layer2): Linear(in_features=3, out_features=1, bias=True),
)
--------------------------------------------------


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [3]:
from minitorch.nn import Linear, Module
from minitorch import Tensor
from minitorch.nn.parameter import Parameter

class MiniTorchModel(Module):
    def __init__(self, in_feat, out_feat):
        super().__init__()
        self.layer1 = Linear(in_feat, 3)
        self.layer2 = Linear(3, out_feat)

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        return x

minitorch_model = MiniTorchModel(2, 1)
print(minitorch_model)

print(minitorch_model.layer1.weight)
print(minitorch_model.layer1.bias)

print(minitorch_model.layer2.weight)
print(minitorch_model.layer2.bias)


MiniTorchModel(
  (layer1): Linear(in_features=2, out_features=3, bias=True),
  (layer2): Linear(in_features=3, out_features=1, bias=True),
)
Parameter containing:
tensor([[ 0.5691,  0.2905, -0.1569],
 [-0.2209, -0.0225, -0.5943]], requires_grad=True)
Parameter containing:
tensor([-0.1912, -0.5565, -0.005 ], requires_grad=True)
Parameter containing:
tensor([[-0.3514],
 [-0.3271],
 [ 0.3505]], requires_grad=True)
Parameter containing:
tensor([-0.1642], requires_grad=True)


In [4]:
print(minitorch_model.parameters())

print('-' * 50)

print(minitorch_model.parameters)
print(minitorch_model.zero_grad())

print(minitorch_model.layer1.weight.grad)

[Parameter containing:
tensor([[ 0.5691,  0.2905, -0.1569],
 [-0.2209, -0.0225, -0.5943]], requires_grad=True), Parameter containing:
tensor([-0.1912, -0.5565, -0.005 ], requires_grad=True), Parameter containing:
tensor([[-0.3514],
 [-0.3271],
 [ 0.3505]], requires_grad=True), Parameter containing:
tensor([-0.1642], requires_grad=True)]
--------------------------------------------------
<bound method Module.parameters of MiniTorchModel(
  (layer1): Linear(in_features=2, out_features=3, bias=True),
  (layer2): Linear(in_features=3, out_features=1, bias=True),
)>
None
tensor(0.)


In [5]:
import torch
import torch.nn as nn

class TorchModel(nn.Module):
    def __init__(self, in_feat, out_feat):
        super().__init__()
        self.layer1 = nn.Linear(in_feat, 3)
        self.layer2 = nn.Linear(3, out_feat)

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        return x

torch_model = TorchModel(2, 1)
out_torch = torch_model(torch.tensor([[1.0] * 2]))


print(torch_model)
print('-' * 50)


print("Torch Model Output:")
print(out_torch)

print('-'*50)

print("Torch Model Parameters:")
for param in torch_model.parameters():
    print(param)

print('-'*50)

t = torch.tensor([[1.0] * 2])
print(t)
print(t.grad)
print(t.requires_grad)

z = torch.tensor([[1.0] * 2], requires_grad=True)
print(z)

# p = torch.nn.Parameter(1.0)
# print(p)

TorchModel(
  (layer1): Linear(in_features=2, out_features=3, bias=True)
  (layer2): Linear(in_features=3, out_features=1, bias=True)
)
--------------------------------------------------
Torch Model Output:
tensor([[1.0611]], grad_fn=<AddmmBackward0>)
--------------------------------------------------
Torch Model Parameters:
Parameter containing:
tensor([[-0.0137, -0.1514],
        [ 0.2542,  0.1472],
        [ 0.3754, -0.0222]], requires_grad=True)
Parameter containing:
tensor([-0.6730,  0.6470,  0.0849], requires_grad=True)
Parameter containing:
tensor([[-0.4224,  0.5471, -0.2996]], requires_grad=True)
Parameter containing:
tensor([0.2647], requires_grad=True)
--------------------------------------------------
tensor([[1., 1.]])
None
False
tensor([[1., 1.]], requires_grad=True)


In [6]:
import minitorch
import minitorch.nn as nn

class MiniTorchModel(nn.Module):
    def __init__(self, in_feat, out_feat):
        super().__init__()
        self.layer1 = nn.Linear(in_feat, out_feat)

    def forward(self, x):
        x = self.layer1(x)
        return x

minitorch_model = MiniTorchModel(2, 1)
print(minitorch_model)

print(nn.Parameter(minitorch_model.layer1.weight))
print(nn.Parameter(minitorch_model.layer1.bias))

input_tensor = minitorch.Tensor([[1.0, 1.0]])
y=minitorch_model(input_tensor)

y.backward()

from minitorch.viz import draw_dot
from IPython.display import display, SVG

# Visualize
dot = draw_dot(y, format='svg')
display(SVG(dot.pipe(format='svg')))


MiniTorchModel(
  (layer1): Linear(in_features=2, out_features=1, bias=True),
)
Parameter containing:
tensor([[-0.5082],
 [-0.1959]], requires_grad=True)
Parameter containing:
tensor([0.4008], requires_grad=True)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

In [7]:
from minitorch.nn.parameter import Parameter
from minitorch.optim import SGD


# Dummy example
w = Parameter(1.0)  # Initial value
w.grad = 0.1        # gradient

opt = SGD([w], lr=0.01)
opt.step()
print(w.data)  # Should be 1.0 - 0.01 * 0.1 = 0.999


0.999


In [8]:
from minitorch.utils.data import Dataset, DataLoader

class MyDataset(Dataset):
    def __init__(self, xs, ys):
        self.xs = xs
        self.ys = ys

    def __getitem__(self, idx):
        return self.xs[idx], self.ys[idx]

    def __len__(self):
        return len(self.xs)

# Dummy data
xs = [i for i in range(10)]
ys = [2 * i + 1 for i in range(10)]


dataset = MyDataset(xs, ys)
print("Dataset length:", len(dataset))
print(dataset)

loader = DataLoader(dataset, batch_size=3, shuffle=True)
print("DataLoader length:", len(loader))
print(loader)

for xb, yb in loader:
    print("Batch x:", list(xb))
    print("Batch y:", list(yb))


Dataset length: 10
Dataset(10)
DataLoader length: 4
DataLoader(batch_size=3, shuffle=True, dataset_size=10)
Batch x: [6, 8, 0]
Batch y: [13, 17, 1]
Batch x: [5, 9, 4]
Batch y: [11, 19, 9]
Batch x: [2, 3, 1]
Batch y: [5, 7, 3]
Batch x: [7]
Batch y: [15]


In [9]:
import minitorch
from minitorch.nn.parameter import Parameter
from minitorch.optim import SGD

# Single-variable linear regression: y = wx + b
w = Parameter(Tensor([0.0]))
b = Parameter(Tensor([0.0]))

def predict(x):
    return w.data * x + b.data

def compute_loss(y_pred, y_true):
    return (y_pred - y_true) ** 2

optimizer = SGD([w, b], lr=0.01)

for epoch in range(10):
    total_loss = 0.0
    for x_batch, y_batch in loader:
        for x, y in zip(x_batch, y_batch):
            x = Tensor(x)
            y = Tensor(y)
            y_pred = predict(x)
            loss = compute_loss(y_pred, y)

            # Manual "backward"
            grad_y_pred = 2.0 * (y_pred - y)
            w.grad = grad_y_pred * x
            b.grad = grad_y_pred * 1.0

            optimizer.step()
            optimizer.zero_grad()

            total_loss += loss.item()
    total_loss /= len(loader)

    print(f"Epoch {epoch+1}: Loss = {total_loss.item():.4f}")


Epoch 1: Loss = 79.7917
Epoch 2: Loss = 0.3185
Epoch 3: Loss = 0.3379
Epoch 4: Loss = 0.2437
Epoch 5: Loss = 0.2216
Epoch 6: Loss = 0.2180
Epoch 7: Loss = 0.1827
Epoch 8: Loss = 0.1744
Epoch 9: Loss = 0.1226
Epoch 10: Loss = 0.1272


In [10]:
import minitorch.nn as nn

class NN(nn.Module):
    def __init__(self, in_feat, out_feat):
        super().__init__()
        self.layer1 = nn.Linear(in_feat, 3)
        self.sign = nn.Sigmoid()
        self.layer2 = nn.Linear(3, out_feat)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.layer1(x)
        x = self.sign(x)
        x = self.layer2(x)
        x = self.relu(x)
        return x
    
minitorch_model = NN(2, 1)
print(minitorch_model)

NN(
  (layer1): Linear(in_features=2, out_features=3, bias=True),
  (sign): Sigmoid(),
  (layer2): Linear(in_features=3, out_features=1, bias=True),
  (relu): ReLU(),
)


In [11]:
import minitorch
from minitorch import nn
from minitorch.optim import Adam
from minitorch import Tensor

import numpy as np
np.random.seed(42)


# Simple model
model = nn.Linear(2, 1)
criterion = nn.MSELoss()
optimizer = Adam(model.parameters(), lr=0.01)

# Dummy data
x = Tensor([[1.0, 2.0], [3.0, 4.0]])
y = Tensor([[1.0], [2.0]])
print("Input data:", x)
print("Target data:", y)
# Training loop


for epoch in range(10):
    y_pred = model(x)
    
    loss = criterion(y_pred, y)
    print(f"Epoch {epoch+1}, Loss: {loss.item()}")
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
print("Final model parameters:")
for param in model.parameters():
    print(param.data)

print("Final model output:")
print(model(x))


Input data: tensor([[1., 2.],
 [3., 4.]], requires_grad=True)
Target data: tensor([[1.],
 [2.]], requires_grad=True)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

import numpy as np
np.random.seed(42)

import torch
torch.manual_seed(42)

# Simple model
model = nn.Linear(2, 1)
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Dummy data (same as minitorch)
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
y = torch.tensor([[1.0], [2.0]])

# Training loop
for epoch in range(10):
    y_pred = model(x)
    loss = criterion(y_pred, y)
    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

# Print final model parameters
print("Final model parameters:")
for param in model.parameters():
    print(param.data)

# Final model output
print("Final model output:")
print(model(x))