In [1]:
import sys
sys.path.append('../')

In [2]:
import minitorch
import torch

In [3]:
a = minitorch.Tensor([[1.0, 2.0], [3.0, 4.0]])
b = minitorch.Tensor([[5.0, 6.0], [7.0, 8.0]])
c = a + b
d = c * a
e = d ** -1
print(e)

t_a = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)
t_b = torch.tensor([[5.0, 6.0], [7.0, 8.0]], requires_grad=True)
t_c = t_a + t_b
t_c.retain_grad()
t_d = t_c * t_a
t_d.retain_grad()
t_e = t_d ** -1
print(t_e)

tensor([[0.1667, 0.0625],
 [0.0333, 0.0208]], requires_grad=True)
tensor([[0.1667, 0.0625],
        [0.0333, 0.0208]], grad_fn=<PowBackward0>)


In [4]:
e.backward()
print(a.grad)
print(b.grad)
print(c.grad)
print(d.grad)

[[-0.19444445 -0.0390625 ]
 [-0.01444444 -0.00694444]]
[[-0.02777778 -0.0078125 ]
 [-0.00333333 -0.00173611]]
[[-0.02777778 -0.0078125 ]
 [-0.00333333 -0.00173611]]
[[-0.02777778 -0.00390625]
 [-0.00111111 -0.00043403]]


In [5]:
t_e.backward(gradient=torch.ones_like(t_e.data, dtype=float))
print(t_a.grad)
print(t_b.grad)
print(t_c.grad)
print(t_d.grad)

tensor([[-0.1944, -0.0391],
        [-0.0144, -0.0069]])
tensor([[-0.0278, -0.0078],
        [-0.0033, -0.0017]])
tensor([[-0.0278, -0.0078],
        [-0.0033, -0.0017]])
tensor([[-0.0278, -0.0039],
        [-0.0011, -0.0004]])
